apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress-mysql
spec:
  selector:
    matchLabels:
      app: wordpress-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-mysql
    spec:
      containers:
      - image: mysql
      # - image: gcr.io/amplified-lamp-378502/mysql:5.7
        name: mysql
        env:    
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: mysql-create-wordpressdb
          valueFrom:
            configMapKeyRef:
              name: mysql-create-wordpressdb
              key: wordpressdb.sql           
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: "mysql-create-wordpressdb"
          mountPath: /script
  
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      - name: mysql-create-wordpressdb
        configMap:
          name: mysql-create-wordpressdb
          defaultMode: 0700