apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: wordpress-mysql
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""  
  volumeName: mysql-pv
  resources:
    requests:
      storage: 10Gi